apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-paul-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:bachu-org/jx3-pipeline-catalog/tasks/hcl/release.yaml@versionStream
          name: ""
          resources:
            # override limits for all containers here
            limits: {}
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
          resources: {}
        - name: next-version
          resources: {}
        - name: jx-variables
          resources: {}
        - name: run-tf
          resources: {}
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 2h0m0s
status: {}

